### PR TITLE
Update deprecated variable names 'enable_accelerated_networking' and 'enabled_ip_forwarding'

### PR DESCRIPTION
**Pull request by rorsgo**
## Describe your changes
Updated the deprecated variable names to the official current ones.

Update variable from 'enabled_ip_forwarding' to '[ip_forwarding_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_interface#ip_forwarding_enabled)'
Update variable from 'enable_accelerated_networking' to '[accelerated_networking_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_interface#accelerated_networking_enabled)'

## Issue number
#73

## Checklist before requesting a review
- [x] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [ ] I have executed pre-commit on my machine
- [ ] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@rorsgo can you format the code (`terraform fmt -recursive`).
@lonegunmanb ptal?

**Comment by rorsgo** [comment]
> @rorsgo can you format the code (`terraform fmt -recursive`). @lonegunmanb ptal?

Done :)

**Comment by davidkarlsen** [comment]
@lonegunmanb ping?

**Comment by exe-r** [comment]
> @exe-r ? @lonegunmanb
> 
> is this still maintained?

@davidkarlsen hopefully one of the maintainers reply.

**Pull request merged**
