### PR TITLE
removed network_security_group_id variable and output as its not needed nor used

### PR DESCRIPTION
**Pull request by juanjojulian**
removed network_security_group_id variable and output as its not needed nor used but prevents the module from working.

## Describe your changes

- removed network_security_group_id variable
- removed remove network_security_group_id output 

## Issue number

#000

## Checklist before requesting a review
- [ X ] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [ X ] I have executed pre-commit on my machine
- [ X ] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Review by lonegunmanb — CHANGES_REQUESTED** [review]
Thanks @juanjojulian for opening this pr! We have a failed test, would you please remove [this assertion](https://github.com/Azure/terraform-azurerm-virtual-machine/blob/main/test/e2e/terraform_test.go#L47-L50) in test? Thanks:

**Comment by juanjojulian** [comment]
While waiting for the approval I added another change, not sure if you prefer to separate changes or group them. Anyway, "admin_username" should be a required variable and should not have a default value because in "azurerm_linux_virtual_machine" admin_ssh_key.username has to match admin_username, otherwise you get the following error from Azure API:

`"Destination path for SSH public keys is currently limited to its default value /home/azureuser/.ssh/authorized_keys  due to a known issue in Linux provisioning agent."`

Maybe a "precondition" to evaluate that admin_username and admin_ssh_key.username should be added.

**Comment by lonegunmanb** [comment]
Thanks @juanjojulian for the latest update, since we're using pr's title as changelog's item, I would prefer a separate pr for `admin_username`.

I've tried this feature, I think we can just remove `username` from `admin_ssh_keys` variable, user `admin_username` as `admin_ssh_keys.username` so we won't have such error, meanwhile our users can customize the username they want to use, WDYT?

**Comment by juanjojulian** [comment]
> Thanks @juanjojulian for the latest update, since we're using pr's title as changelog's item, I would prefer a separate pr for `admin_username`.

OK, I  understand, reverted last commit and pushed again to the branch.
> 
> I've tried this feature, I think we can just remove `username` from `admin_ssh_keys` variable, user `admin_username` as `admin_ssh_keys.username` so we won't have such error, meanwhile our users can customize the username they want to use, WDYT?

Sounds good to me, makes life easier to users. I can work on it and test it if you agree.

**Comment by lonegunmanb** [comment]
> > Thanks @juanjojulian for the latest update, since we're using pr's title as changelog's item, I would prefer a separate pr for `admin_username`.
> 
> OK, I understand, reverted last commit and pushed again to the branch.
> 
> > I've tried this feature, I think we can just remove `username` from `admin_ssh_keys` variable, user `admin_username` as `admin_ssh_keys.username` so we won't have such error, meanwhile our users can customize the username they want to use, WDYT?
> 
> Sounds good to me, makes life easier to users. I can work on it and test it if you agree.

It would be nice if you can submit a separate pr for this change, thank you so much for your help!

**Review by lonegunmanb — APPROVED** [review]
Thanks @juanjojulian, LGTM! 🚀

**Pull request merged**
